### ISSUE TITLE
Don't throw strings

### ISSUE THREAD

**Issue by LoganDark** [hogeschool/Development-8#3]
https://github.com/hogeschool/Development-8/blob/3c90d48a73c69bb5ef897b66a88d75bd99ce401d/Code/Unit2ts/unit2.ts#L65 and https://github.com/hogeschool/Development-8/blob/3c90d48a73c69bb5ef897b66a88d75bd99ce401d/Code/Unit2ts/unit2.ts#L122

#2 fixes this. I think you should throw [`TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)s instead.

Imagine this:

```ts
try {
    console.log ( last ( Empty () ) )
} catch ( e ) {
    console.error ( e )
}
```

In the console, you would get `The list is empty` outputted to stderr, but where did it come from? Nobody would know! There would be no stack trace! In contrast, `console.error ( new TypeError ( 'message here' ) )` gives a full stack trace. It's better than a string.

**Comment by ghost** [comment]
Indeed, but these are just exercises not a big project. So it would be pretty easy to know where it came from.

**Comment by LoganDark** [comment]
Possibly, but in my eyes, using that as an excuse to write bad code is unacceptable. Just saying.

**Comment by ghost** [comment]
If you write a throwaway project it would be arguably overkill to use many software principles (such as SOLID). I do get your point though but still these are just exercises.

**Comment by LoganDark** [comment]
If you write a throwaway project for the sake of being bad, by all means do it. However, if you're writing a "throwaway project" for a course, that you will use to teach students, you should try to educate them on good practices.

Learning to throw errors is also a very important skill. Please don't understate its importance by implying that this is a throwaway project and because of that good coding practices go down the drain.

I don't mean to offend anyone, but good coding practices are important, whether you're writing one hundred lines of code, or one million.

**Comment by FDigiacomo** [comment]
TypeError to signal that a list is empty does not look like a clean solution to me as well, since, as the name suggests, it is a type error. If we really want to be accurate, we should define a custom exception and throw that instead.

Moreover, since this is a course about **Functional Programming**, throwing exceptions is a bad practice in general (and not only in functional programming). But, in order to explain you how to handle errors in pure functional programming, I would need to explain how Functors and Monads work  (Functors were partially introduced at the end of the course) and then you should use the Sum monad. This would require me to teach a total of (currently in this school) 12 study points, which are currently spread among dev8, infsen1, and infsen2, in a period of 8 weeks. Furthermore, in class we explained an alternative approach to that solution that returns Option<a> and handles that case properly, but that exercise is for a lesson that came BEFORE .

Finally, we tend to avoid to overcomplicate exercise solutions since there is a number of people who struggle with basic recursion, so knowing how to handle an exception in javascript/typescript properly is not exactly the goal of this course.

**Comment by LoganDark** [comment]
> TypeError to signal that a list is empty does not look like a clean solution to me as well, since, as the name suggests, is a type error

Before your comment, I modified the pull request to use `Error` instead (and I do agree a custom error type would be helpful).

Since you're specifically teaching functional programming, I guess attempting to explain why OOP is better in this case would be quite foolish of me.

Since you *are* throwing errors, I think it *should* be done right. If you're going to throw strings, I can't tell you otherwise. You do you.

**Comment by FDigiacomo** [comment]
Unsuccessful troll is unsuccessful

**Comment by LoganDark** [comment]
Please explain to me how this is trolling?

**Comment by FDigiacomo** [comment]
Figure it out since you know everything

**Comment by FDigiacomo** [comment]
Also throwing Error is bad practice again because it is like throwing Exception in .NET or Java. You are throwing the most general exception possible.

**Comment by LoganDark** [comment]
I apologize if it seems like I'm trolling. Honestly, it would be better if you just ignore everything I've said earlier.
